### PR TITLE
Update supported python versions and clean up pre-commit hooks

### PR DESCRIPTION
**Pull request by drewoldag**
**Updates supported python version in workflows.** 
Changes the requested python versions in all the relevant CI workflows from 3.8-3.10 to 3.9-3.11

**Specify minimum python in pyproject.toml**
States the minimum required version of python >3.9 in both pyproject.toml files. The one for this template, and the one that is used when hydrating a new project. 

**Clean up pre-commit.yml**
Removes the unnecessary check for updates that have occurred in the LINCC Frameworks PPT. Moves the pytest check to the last step (since that usually takes longer) and it's usually other hooks that fail (i.e.  pylint)

### CODE REVIEW

**Review by eacharles — APPROVED** [review]
Does this still have the pre-commit stuff?   Otherwise all good.

**Comment by drewoldag** [comment]
Yes, it does still include pre-commit. stuff. I personally find it very helpful to have pre-commit hooks, and would advocate for them to be included. 

I would also offer that, when a user configures their environment, if they *do not* run `pre-commit install` then pre-commit hooks will not be run prior to a git commit. 

Would leaving pre-commit in but not initializing it in your environment satisfy your preferred workflow? I would be happy to update the documentation about that as well.

**Comment by eacharles** [comment]
I guess there isn't any easy way to have some people to use them without having them in the template.   

The other reason I'm not really a fan of them is that they impose process on people and I have usually found that to actually be long-term counter-productive when working in an academic environment.    But yes, if we just set it up so that they are there, and we tell people that they are available as a tool, but don't suggest that it is some how a "required thing" then sure.

**Comment by drewoldag** [comment]
Sure, that makes sense to me. I'll leave them as they are in this PR, and I'll review the readme for this repo as well, and update references to pre-commit there before merging.

**Pull request merged**
